package:
  name: aat_downloader
  version: 0.0.3
source:
  sha256: 9c5a9fd2777b1a38d68eb7a2a07589639071a83f76bb20edee193814cd6f811b
  url: https://files.pythonhosted.org/packages/89/f6/3eb049f5dc7fe9692af2c6ba57c6d652ddae1028735a5d6f8cafa35c578c/aat_downloader-0.0.3.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: A downloader for mobile aat data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - pyrebase
  - pandas
  run:
  - pip
  - python
  - packaging
  - pyrebase
  - pandas
test:
  imports:
  - aat_downloader
