package:
  name: aat_downloader
  version: 0.0.2
source:
  sha256: 65a660cc5c5e4d4bda5d739fb36351117a2c54cd59f137f92366e7985a0511c6
  url: https://files.pythonhosted.org/packages/95/80/d2fde04f80b94c5ec3c7863b87893e3319ec6110defaf9973e5602b5ffa1/aat_downloader-0.0.2.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: A downloader for mobile aat data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - pyrebase
  - pandas
  run:
  - pip
  - python
  - packaging
  - pyrebase
  - pandas
test:
  imports:
  - aat_downloader
